'use server';

/**
 * @fileOverview Filters solver submissions based on metrics like plagiarism and code similarity.
 *
 * - filterSolverSubmissions - A function that filters solver submissions.
 * - FilterSolverSubmissionsInput - The input type for the filterSolverSubmissions function.
 * - FilterSolverSubmissionsOutput - The return type for the filterSolverSubmissions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FilterSolverSubmissionsInputSchema = z.object({
  submissionText: z.string().describe('The text of the solver submission.'),
  codeSnippet: z.string().optional().describe('The code snippet of the solver submission, if applicable.'),
  referenceMaterial: z
    .string()
    .describe('Reference material to check against for plagiarism and code similarity.'),
});

export type FilterSolverSubmissionsInput = z.infer<typeof FilterSolverSubmissionsInputSchema>;

const FilterSolverSubmissionsOutputSchema = z.object({
  plagiarismScore: z
    .number()
    .describe('A score indicating the level of plagiarism detected (0-1, 1 being highly plagiarized).'),
  codeSimilarityScore: z
    .number()
    .describe('A score indicating the level of code similarity detected (0-1, 1 being highly similar).'),
  aiGeneratedContentScore: z
    .number()
    .describe('A score indicating the likelihood that the submission was generated by AI (0-1, 1 being highly likely).'),
  isAcceptable: z
    .boolean()
    .describe('Whether the submission is acceptable based on the plagiarism and similarity scores.'),
  justification: z.string().describe('A justification for the isAcceptable decision.'),
});

export type FilterSolverSubmissionsOutput = z.infer<typeof FilterSolverSubmissionsOutputSchema>;

export async function filterSolverSubmissions(
  input: FilterSolverSubmissionsInput
): Promise<FilterSolverSubmissionsOutput> {
  return filterSolverSubmissionsFlow(input);
}

const filterSolverSubmissionsPrompt = ai.definePrompt({
  name: 'filterSolverSubmissionsPrompt',
  input: {schema: FilterSolverSubmissionsInputSchema},
  output: {schema: FilterSolverSubmissionsOutputSchema},
  prompt: `You are an AI assistant that reviews solver submissions for plagiarism, code similarity, and AI-generated content.

  You will be provided with the submission text, code snippet (if applicable), and reference material.
  You will output a plagiarism score, code similarity score, AI-generated content score, whether the submission is acceptable, and a justification for your decision.

  Submission Text: {{{submissionText}}}
  Code Snippet: {{{codeSnippet}}}
  Reference Material: {{{referenceMaterial}}}

  Given the above information, determine the plagiarismScore, codeSimilarityScore, aiGeneratedContentScore, isAcceptable, and justification.
  The plagiarismScore should reflect the degree to which the Submission Text plagiarizes the Reference Material, and should be in the range of 0 to 1.
  The codeSimilarityScore should reflect the degree to which the Code Snippet is similar to code in the Reference Material, and should be in the range of 0 to 1.
  The aiGeneratedContentScore should reflect the likelihood that the Submission Text and Code Snippet (if present) were generated by AI, and should be in the range of 0 to 1.
  The isAcceptable field should indicate whether the submission is acceptable based on the plagiarism and similarity scores.
`,
});

const filterSolverSubmissionsFlow = ai.defineFlow(
  {
    name: 'filterSolverSubmissionsFlow',
    inputSchema: FilterSolverSubmissionsInputSchema,
    outputSchema: FilterSolverSubmissionsOutputSchema,
  },
  async input => {
    const {output} = await filterSolverSubmissionsPrompt(input);
    return output!;
  }
);
